name: Coverage Report
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    with:
      system_deps: "ffmpeg"
      test_extras: "test"
      test_path: "test/"
    secrets: inherit
